### ISSUE TITLE
funcpack doesn't work for alpine and ubuntu

### ISSUE THREAD

**Issue by dejanvasic85** [christopheranderson/azure-functions-pack#18]
To replicate: 

``` npm install -g azure-functions-pack ```

``` funcpack pack -u ./ ```

Returns:
'no such file or directory'

![image](https://cloud.githubusercontent.com/assets/1418428/24536296/384e5154-1625-11e7-8ae5-2357052ecc5e.png)

This is a show-stopper as we are using BuildKite agent with docker image to build and publish our azure functions.

**Comment by FastNinja** [comment]
@christopheranderson is that intended? with Microsoft reaching out to open source community and adding support for Linux everywhere one might think that Azure functions (and `function-packers`) shall work under Linux/Ubuntu.

**Comment by christopheranderson** [comment]
Not intended. Only tested on Windows 10 PowerShell and Mac terminal. This is a bug.

**Comment by smil2k** [comment]
Hi,

I just created a pull request for this. (At least the fix for "No such file or directory").

Still running it returns error:
$ funcpack pack .
/usr/lib/node_modules/azure-functions-pack/lib/packhost-generator.js:132
            for (const [name, fx] of this.functionsMap) {
                       ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/azure-functions-pack/lib/index.js:6:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

$ npm -v
2.15.5
$ node -v
v4.4.6
