### ISSUE TITLE
Issues running on past versions of node. was: Failed Optional Dependency fsevents

### ISSUE THREAD

**Issue by Stewartarmbrecht** [christopheranderson/azure-functions-pack#5]
I am running on Windows 8.1 Enterprise x64 and I get the following error when I try to npm install...

npm WARN optional Skipping failed optional dependency /azure-functions-pack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

Any idea what might be the problem?

I get this error when I run funcpack

for (const [name, fx] of this.functionsMap) {
                       ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\stearm01\AppData\Roaming\npm\node_modules\azure-functions-pack\lib\index.js:5:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

**Comment by Stewartarmbrecht** [comment]
Ran with out error on Windows 10:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\azure-functions-pack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

C:\Users\stewa\Source\Repos\tococms-api>funcpack
info: Generating project files/metadata
info: Webpacking project
info: Complete!

**Comment by christopheranderson** [comment]
That's just a warning. That's not an issue to be concerned with on Windows. The biggest issue ends up being that you need Node v6 or I think some of the es6 features I'm using won't work
